resolver: lts-16.21

packages:
- clash-prelude
- clash-lib
- clash-ghc
- clash-cores
- testsuite
- clash-term

flags:
    clash-prelude:
      multiple-hidden: false

    clash-lib:
      history: true

extra-deps:
- ./clash-cosim
- concurrent-supply-0.1.8@sha256:9373f4868ad28936a7b93781b214ef4afdeacf377ef4ac729583073491c9f9fb,1627
- ghc-typelits-extra-0.4@sha256:e1ba4ebf14cb7025dd940380dfb15db444f7e8bced7e30bdad6e1707f0af7622,4813
- rewrite-inspector-0.1.0.11
- brick-0.50

